version: '3'

services:
  # =========ローカルと本番切り替え===========
  db:
    platform: linux/x86_64
    image: mysql:5.7
    networks:
      - mainnet2
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: kumatabetai1107
      MYSQL_USER: user
      MYSQL_PASSWORD: kumatabetai1107
      MYSQL_DATABASE: mainapp_development
  # ======================================

  app:
    build: .
    # Dockerfileのあるディレクトリを指定
    # =========ローカルと本番切り替え===========
    # command: bundle exec puma -C config/puma.rb -e production
    command: bundle exec puma -C config/puma.rb
    depends_on:
      - db
    # ======================================
    networks:
      - mainnet2
    volumes: 
      - .:/mainapp
      # - ローカル側の同期させたいディレクトリ : コンテナ側の同期させたいディレクトリ
      # .( docker-compose.ymlのあるディレクトリ、つまりローカル側のmainapp配下 ) と /mainapp/( コンテナ側のmainapp配下 ) を同期
      # ローカルのmainapp配下のファイルなどを編集すると、コンテナ側にも編集が反映
      - public-data:/mainapp/public
      - tmp-data:/mainapp/tmp
      - log-data:/mainapp/log

  web:
    build: ./nginx_docker
    # Dockerfileのあるディレクトリを指定
    depends_on:
      - app
    networks:
      - mainnet2
    ports:
      - 80:80
    volumes: 
      - public-data:/mainapp/public
      - tmp-data:/mainapp/tmp

networks:
  mainnet2:
    external: true

volumes:
  db-data:
  public-data:
  tmp-data:
  log-data:
